apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJxdWF5LmlvIjogewoJCQkiYXV0aCI6ICJhV0Z0WVhCcGEyVjVPZz09IgoJCX0KCX0KfQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: quay-io-imagepullsecret
type: kubernetes.io/dockerconfigjson
